name = "parakeet-facility-backend"
main = "src/index.ts"
compatibility_date = "2024-12-15"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "my-variable"
[env.dev]
DATABASE_URL = "my-variable"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
[[r2_buckets]]
binding = 'PARAKEET_FACILITY_IMAGES_BUCKET'
bucket_name = 'parakeet-facility-images'
preview_bucket_name = 'parakeet-facility-images'
